

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB}}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

cv.service.url=https://verikyc-cv-<your-hash>.us-central1.run.app

# gcs
gcs.bucket.name=${GCS_BUCKET_NAME}