spring.application.name=repo-verikyc-backend

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
jwt.secret=${JWT_SECRET}
jwt.expiry=${JWT_EXPIRY_MS}

spring.data.web.pageable.default-page-size=10

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never